#!/usr/bin/env php
<?php
/*
 * @Author: cclilshy jingnigg@163.com
 * @Date: 2022-12-06 16:22:36
 * @LastEditors: cclilshy cclilshy@163.com
 * @FilePath: /ccphp/master
 * @Description: My house
 * Copyright (c) 2022 by cclilshy email: jingnigg@163.com, All Rights Reserved.
 */

use core\Master;

include __DIR__ . '/core/Base/ccload.php';
Master::rouse('Ccphp\Ccphp');
Master::rouse('Route\Route');
Master::rouse('Console')->run();